spring:
  config:
    activate:
      on-profile: [application.yml에 선언할 프로파일값 ex. dev_secret, env_secret]
  datasource:
    url: jdbc:postgresql://[DB주소]/[DB명]
    username: DB 아이디
    password: DB 비밀번호
